### ISSUE TITLE
Using Apache

### ISSUE THREAD

**Issue by LauraMares** [rohit-cubix/php-socket-chat#1]
Hello!! 

I am trying to test your project, but after installing and logging in, I just see an empty screen with a light blue background and nothing on it. I am using the Apache Server and I installed it using Xampp, and I am not sure if it goes as a VPS or multiport server.

Also, could you please explain this part: "Need to open extra port on the server for chat, which need to assign in configuration."

Thank you.

Sorry if it's not the most appropriate way to ask you these questions.

**Comment by remorr25** [comment]
If you testing on local machine using xampp then you have to run the server.php using CMD/Terminal. you can find the port number inside include/define_var.php file. If you want to change the port you can change, but you have to change the socket connection port number in index.php file.
